from copy import deepcopy
from pathlib import Path
from docx import Document

REFERENCE = Path(r"C:\Users\chuak\Downloads\Test-Case-Template (1).docx")
OUTPUT = Path(r"C:\Users\chuak\Desktop\menrosystem\MENRO-Test-Cases-September-30-2026.docx")

cases = [
    ["TC-AUTH-001", "Verified participant can log in using email and password", "REQ-AUTH-01", "Authentication", "System", "H", "Critical", "An active participant account exists and its email is verified", "Valid participant email and password", "1) Open the login page\n2) Enter the verified email and password\n3) Click Login\n4) Open a protected participant page", "Firebase signs in the participant, the backend verifies the ID token and active profile, and the participant dashboard opens", "Login succeeds; role comes from the backend profile; protected participant route is accessible", ""],
    ["TC-AUTH-002", "New participant can sign in using Google and complete the profile", "REQ-AUTH-02", "Google Sign-In and Profile", "Integration", "H", "Major", "A Google account not yet registered in the system is available", "Google account and required participant profile details", "1) Click Continue with Google\n2) Choose the Google account\n3) Allow the system to create the participant profile\n4) Complete the required profile fields", "A participant profile is created with participant role and the user is sent to profile completion before protected features", "No privileged role can be selected; completed profile is saved under the authenticated UID", ""],
    ["TC-AUTH-003", "Unverified email and password participant is blocked", "REQ-AUTH-03", "Email Verification", "Integration", "H", "Critical", "An active participant account exists but its email is not verified", "Unverified participant credentials", "1) Sign in using the unverified account\n2) Attempt to open a protected API-backed page\n3) Request a new verification email", "The backend denies protected access and the UI explains that email verification is required", "Protected request returns 403; no participant data is returned; resend verification action is available", ""],
    ["TC-SEC-004", "Client role values cannot bypass backend authorization", "REQ-SEC-01", "Role-Based Authorization", "Integration", "H", "Critical", "An active participant account and an Admin-only endpoint are available", "Participant ID token with a modified or spoofed frontend role value", "1) Change the client-side role value to admin\n2) Call an Admin-only endpoint directly\n3) Inspect the response", "The backend reads the role from the stored user profile and denies the participant", "Request returns 403 and no privileged action or data change occurs", ""],
    ["TC-USER-005", "Admin can manage user role and account status", "REQ-USER-01", "User Management", "Integration", "H", "Critical", "An Admin account and a target user account exist", "Target UID; valid role; active and inactive status values", "1) Open Registered Users\n2) Change the target user's role\n3) Set the account to inactive\n4) Attempt to use the inactive account", "Role and status changes are saved with an audit record, and inactive access is denied", "Only Admin can change role or status; audit log stores actor and old and new values; inactive token is rejected", ""],
    ["TC-REQ-006", "Participant submits a valid seedling request", "REQ-REQ-01", "Seedling Requests", "System", "H", "Major", "Participant profile is complete; active inventory and planting site in the same barangay exist", "Species and quantity, barangay, planting site, proposed date, and expected participants", "1) Open Request Seedlings\n2) Select available seedlings and quantities\n3) Select the matching planting site\n4) Enter event details\n5) Submit", "One Pending request is created with its request number, requested items, site, and event proposal", "HTTP 201; request appears in My Requests; mismatched barangay and site combinations are rejected", ""],
    ["TC-REQ-007", "Staff review and Admin approval create a scheduled event", "REQ-REQ-02", "Request Review and Event Creation", "Integration", "H", "Critical", "A valid Pending request exists", "Staff account, Admin account, request ID", "1) Review the request as Staff\n2) Confirm the request becomes Reviewed\n3) Approve it as Admin\n4) Open the event calendar", "The request becomes Approved and a linked scheduled event is created without deducting stock", "Review and decision roles remain separate; event keeps source request and allocation details; inventory is unchanged until release", ""],
    ["TC-DIST-008", "Staff release updates inventory, distribution, event allocation, and notification atomically", "REQ-DIST-01", "Distribution and Inventory", "Integration", "H", "Critical", "An Approved request and sufficient active inventory exist", "Approved request with one or more release quantities", "1) Release the approved request as Staff\n2) Open inventory\n3) Open distributions and the linked event\n4) Check participant notifications", "Stock is deducted once, a Released distribution is created, event allocation is marked released, and the participant is notified", "All linked records agree on released quantities; invalid release leaves every record unchanged; repeated release does not duplicate the transaction", ""],
    ["TC-PHOTO-009", "Planting evidence requires original EXIF GPS and never substitutes device GPS", "REQ-PHOTO-01", "Planting Report Photo Verification", "System", "H", "Critical", "Participant has a released event allocation and a registered planting site", "Original geotagged image and a separate image without EXIF GPS", "1) Select Take Photo or Upload Existing Photos\n2) Confirm previews appear\n3) Submit the geotagged image\n4) Try the non-geotagged image while device coordinates are available", "The original photo can be uploaded and verified from its metadata; the non-geotagged photo remains previewable but cannot be accepted as location proof", "Server stores photo EXIF coordinates; client or device coordinates do not replace missing EXIF GPS; the UI separates upload validity from location verification", ""],
    ["TC-PHOTO-010", "Photo outside the registered planting site is submitted for MENRO review", "REQ-PHOTO-02", "Geo-Tag Verification", "Integration", "H", "Major", "A valid original photo contains GPS inside Juban but outside the assigned site", "Photo EXIF coordinates outside the site polygon or radius", "1) Upload the photo\n2) Review the location message and map\n3) Submit the report\n4) Open the report as Staff or Admin", "The system preserves the real EXIF coordinates, marks the submission Needs Review, and keeps the image visible", "No silent verification occurs; distance and site mismatch are shown; authorized reviewer can accept or reject the submission", ""],
    ["TC-PHOTO-011", "Duplicate planting image is rejected", "REQ-PHOTO-03", "Duplicate Evidence Detection", "Integration", "H", "Major", "A planting image has already been saved as evidence", "The exact same image bytes uploaded again", "1) Submit the original image once\n2) Upload the same file in another planting submission\n3) Inspect the response and records", "The second upload is rejected as duplicate evidence", "Duplicate hash is detected; no duplicate photo file, contribution, or quantity is counted", ""],
    ["TC-REPORT-012", "Staff or Admin accepts or rejects a submission needing review", "REQ-REPORT-01", "Planting Report Review", "Integration", "H", "Critical", "A planting contribution has Needs Review and Pending Review statuses", "Reviewer UID; acceptance remarks or rejection reason", "1) Open the planting report details\n2) Select the flagged submission\n3) Accept it and verify totals\n4) Repeat with another submission and reject with a reason", "Acceptance counts the quantity without hiding automated findings; rejection records the reason and reopens the quantity for reporting", "Authenticated reviewer and time are saved; verification result stays truthful; parent progress and event quantities are recalculated", ""],
    ["TC-MON-013", "Participant records scheduled tree survival monitoring using EXIF evidence", "REQ-MON-01", "Tree Survival Monitoring", "System", "H", "Major", "A completed planting report is eligible and its monitoring date is due", "Healthy, damaged, and dead counts; maturity status; remarks; original geotagged monitoring photo", "1) Open Survival Monitoring\n2) Select the eligible report\n3) Enter condition counts and maturity\n4) Upload and verify the monitoring photo\n5) Submit", "A monitoring history entry is added with survival rate, EXIF location comparison, remarks, and next monitoring date", "Counts equal planted quantity; non-geotagged image is rejected; next date follows the schedule; monitoring ends after the two-year criterion", ""],
    ["TC-AN-014", "Dashboard and analytics use connected operational records", "REQ-AN-01", "Dashboard and Analytics", "System", "M", "Major", "Released distributions, completed or reviewed planting submissions, sites, events, and monitoring records exist", "Barangay and date filters", "1) Open the management dashboard\n2) Compare seedlings, distributed, planted, survival, report, and event KPIs with source records\n3) Change filters\n4) Inspect charts and maps", "KPIs, trends, barangay coverage, survival values, event statistics, and map markers update from the same filtered records", "No invented chart points; totals agree with source records; empty filters show an understandable no-data state", ""],
    ["TC-PDF-015", "Authorized user generates and downloads a PDF report", "REQ-REP-01", "Reports and PDF Download", "System", "H", "Major", "Staff or Admin is signed in and qualifying system records exist", "Report type and valid date range or event filter", "1) Open Reports\n2) Choose a report type and filters\n3) Generate the report\n4) Download the PDF\n5) Attempt the same endpoint as Participant", "A report history record and downloadable PDF are produced for Staff or Admin; Participant access is denied", "PDF response uses application/pdf and expected filename; report uses real filtered rows; unauthorized request returns 403", ""],
]

doc = Document(REFERENCE)
info = doc.tables[0]
info.cell(0, 1).text = "Web-Based Geo-Tagged Reforestation Monitoring System for the Municipal Environment and Natural Resources Office of Juban, Sorsogon"
info.cell(1, 1).text = ""
info.cell(2, 1).text = "September 30, 2026"
info.cell(3, 1).text = ""

table = doc.tables[1]
for idx, values in enumerate(cases, start=2):
    row = table.rows[idx]
    for col, value in enumerate(values):
        cell = row.cells[col]
        cell.text = value
        source_cell = table.rows[1].cells[col]
        if source_cell.paragraphs and cell.paragraphs:
            source_p = source_cell.paragraphs[0]
            target_p = cell.paragraphs[0]
            target_p.alignment = source_p.alignment
            target_p.paragraph_format.left_indent = source_p.paragraph_format.left_indent
            target_p.paragraph_format.right_indent = source_p.paragraph_format.right_indent
            target_p.paragraph_format.space_before = source_p.paragraph_format.space_before
            target_p.paragraph_format.space_after = source_p.paragraph_format.space_after
            for run in target_p.runs:
                if source_p.runs:
                    run._element.get_or_add_rPr()
                    source_rpr = source_p.runs[0]._element.rPr
                    if source_rpr is not None:
                        run._element.replace(run._element.rPr, deepcopy(source_rpr))

doc.save(OUTPUT)
print(OUTPUT)
